import type { Config } from 'tailwindcss'

const config: Config = {
  content: ['./src/**/*.{js,ts,jsx,tsx,mdx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        surface: '#fbfaee',
        'secondary-fixed': '#ffe088',
        'on-surface-variant': '#424655',
        'primary-container': '#1e6bff',
        'on-tertiary-container': '#fffeff',
        'outline-variant': '#c2c6d8',
        'tertiary-fixed-dim': '#ffb3b1',
        'on-error-container': '#93000a',
        secondary: '#735c00',
        'error-container': '#ffdad6',
        'surface-dim': '#dbdbcf',
        'on-secondary-fixed': '#241a00',
        'on-tertiary-fixed': '#410007',
        'on-secondary': '#ffffff',
        'inverse-primary': '#b3c5ff',
        'surface-bright': '#fbfaee',
        'on-secondary-fixed-variant': '#574500',
        'on-primary-container': '#fffeff',
        outline: '#737687',
        'on-error': '#ffffff',
        error: '#ba1a1a',
        tertiary: '#b9132b',
        'on-secondary-container': '#745c00',
        'tertiary-fixed': '#ffdad8',
        'on-background': '#1b1c15',
        'surface-container-low': '#f5f4e8',
        'secondary-container': '#fed65b',
        'on-surface': '#1b1c15',
        background: '#fbfaee',
        'primary-fixed-dim': '#b3c5ff',
        'inverse-on-surface': '#f2f1e5',
        'surface-tint': '#0054d7',
        'surface-container-highest': '#e4e3d7',
        'surface-container-high': '#e9e9dd',
        'on-tertiary-fixed-variant': '#92001c',
        'surface-container-lowest': '#ffffff',
        'inverse-surface': '#303129',
        'primary-fixed': '#dbe1ff',
        'on-primary-fixed-variant': '#003fa5',
        'surface-variant': '#e4e3d7',
        'secondary-fixed-dim': '#e9c349',
        'surface-container': '#efeee3',
        primary: '#0053d4',
        'on-tertiary': '#ffffff',
        'on-primary': '#ffffff',
        'tertiary-container': '#dd3240',
        'on-primary-fixed': '#001849',
        'on-tertiary-fixed-dim': '#ffb3b1',
        'surface-container-low-opacity': 'rgba(245,244,232,0.9)',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        xs: '4px',
        xl: '80px',
        lg: '48px',
        sm: '12px',
        'margin-mobile': '16px',
        base: '8px',
        'margin-desktop': '64px',
        md: '24px',
        gutter: '24px',
      },
      fontFamily: {
        'headline-lg-mobile': ['var(--font-plus-jakarta)', 'system-ui', 'sans-serif'],
        'headline-md': ['var(--font-plus-jakarta)', 'system-ui', 'sans-serif'],
        'headline-lg': ['var(--font-plus-jakarta)', 'system-ui', 'sans-serif'],
        'headline-xl': ['var(--font-plus-jakarta)', 'system-ui', 'sans-serif'],
        'label-sm': ['var(--font-plus-jakarta)', 'system-ui', 'sans-serif'],
        'label-lg': ['var(--font-plus-jakarta)', 'system-ui', 'sans-serif'],
        'body-md': ['var(--font-be-vietnam)', 'system-ui', 'sans-serif'],
        'body-lg': ['var(--font-be-vietnam)', 'system-ui', 'sans-serif'],
      },
      fontSize: {
        'headline-lg-mobile': ['28px', { lineHeight: '36px', fontWeight: '700' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'label-sm': ['12px', { lineHeight: '16px', fontWeight: '500' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'headline-lg': ['32px', { lineHeight: '40px', fontWeight: '700' }],
        'label-lg': ['14px', { lineHeight: '20px', fontWeight: '600' }],
        'headline-xl': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '800' }],
      },
    },
  },
  plugins: [],
}

export default config
